### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-jwtool#1]
Now that we're potentially using this in [mozilla/fxa-auth-server](https://github.com/mozilla/fxa-auth-server/pull/902/files) for reals, we may want to add a README.md so people (like me) know what this does...

**Comment by dannycoates** [comment]
![fine](http://i.giphy.com/NvPvesMZtbiRa.gif)

**Comment by dannycoates** [comment]
@pdehaan happy now? https://github.com/mozilla/fxa-jwtool/blob/master/README.md

**Comment by pdehaan** [comment]
@dannycoates,

![YAS!](https://31.media.tumblr.com/66f851f331504ac7baf0862df67d9422/tumblr_inline_nln398k68P1r79k32.gif)

**Comment by pdehaan** [comment]
Closing. Fixed by 7e96ef55bfb12103b9d654180905f03116d02be4
